backend:
  name: github
  repo: trannhukhoinguyen/zero-mind
  branch: main
  auth_scope: repo
  base_url: https://your-auth-server.com
  auth_endpoint: oauth/authorize
  token_endpoint: oauth/token

collections:
  - name: "exercises"
    label: "Exercises"
    folder: "src/content/exercises"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text, required: false }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: authors, label: Authors, widget: list, required: false }
      - { name: draft, label: Draft, widget: boolean, required: false }

  - name: "doubts"
    label: "Doubts"
    folder: "src/content/doubts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text, required: false }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: authors, label: Authors, widget: list, required: false }
      - { name: draft, label: Draft, widget: boolean, required: false }

  - name: "koans"
    label: "Koans"
    folder: "src/content/koans"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text, required: false }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: authors, label: Authors, widget: list, required: false }
      - { name: draft, label: Draft, widget: boolean, required: false }

media:
  input: public/static
  output: public/static



