content:
  - name: doctrines
    label: Doctrines
    path: src/content/projects
    filename: '{name}.md'
    type: collection
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: name
        label: Title
        type: string

      - name: description
        label: Description
        type: text

      - name: startDate
        label: Start Date
        type: date
        options:
          format: MM/dd/yyyy

      - name: image
        label: Image
        type: image

      - name: body
        label: Body
        type: rich-text

media:
  input: public/static
  output: public/static



